### PR TITLE
make sure p2pool is compliant with the cltv softfork

### PR DESCRIPTION
**Pull request by jameshilliard**
With the cltv softfork upcoming I've bumped the minimum bitcoind version requirement and changed the the block version check to reflect fork compatibility. Since blocks with version 536870919 are produced by a client(BitcoinXT) that does not enforce cltv and since the version number is higher than 3 those blocks will get orphaned when 75% of the network is producing v4 blocks.

### CODE REVIEW

**Comment by jtoomim** [comment]
BitcoinXT should be supporting BIP65 soon. https://github.com/bitcoinxt/bitcoinxt/issues/93

I don't know if the version check for 0.11.2 will work with XT yet, since I don't know what XT's version number will be. I'll check in here once that has been decided.

I think it may be necessary to softfork the p2pool share chain to prevent non-compliant miners from mucking up the share chain. @jameshilliard you could check at the commit history to see how forrestv implemented the BIP66 fork for inspiration.

**Comment by jameshilliard** [comment]
> I don't know if the version check for 0.11.2 will work with XT yet, since I don't know what XT's version number will be. I'll check in here once that has been decided.

It just needs to be higher than core's version number.

> I think it may be necessary to softfork the p2pool share chain to prevent non-compliant miners from mucking up the share chain.

Found it, I bumped the protocol version.

**Comment by forrestv** [comment]
Thank you for the change. There will be a P2Pool hardfork coming up soon which will ensure that all remaining nodes are using this. However, triggering a hardwork is more complicated than just bumping the protocol version. Can you change this patch back to just establishing BIP65 compatibility?

**Comment by jameshilliard** [comment]
> Can you change this patch back to just establishing BIP65 compatibility?

I removed the p2pool version bump commit.

**Pull request merged**
