### PR TITLE
Look for bip65 in softfork instead of version number comparison

### PR DESCRIPTION
**Pull request by Hannott**

### CODE REVIEW

**Comment by Hannott** [comment]
XT 0.11C does not have the 'softforks' and will throw an exception. Tested with XT 0.11C, 0.11D (latest build), Core 0.11 and 0.11.2. Got expected results in all cases

**Comment by ChainQuery** [comment]
Interesting solution, do we know how long getblockchaininfo will report each softfork's status?

**Comment by jameshilliard** [comment]
@ChainQuery even the BIP34 soft fork appears under getblockchaininfo still so I suspect for a while

**Comment by Hannott** [comment]
@jameshilliard @ChainQuery This is hard coded in the getblockchaininfo rpc call.

https://github.com/bitcoin/bitcoin/blob/8e598dc4ea1da92d34c8d964060d1d72f4465370/src/rpcblockchain.cpp#L657

    const Consensus::Params& consensusParams = Params().GetConsensus();
    CBlockIndex* tip = chainActive.Tip();
    UniValue softforks(UniValue::VARR);
    softforks.push_back(SoftForkDesc("bip34", 2, tip, consensusParams));
    softforks.push_back(SoftForkDesc("bip66", 3, tip, consensusParams));
    softforks.push_back(SoftForkDesc("bip65", 4, tip, consensusParams));
    obj.push_back(Pair("softforks",             softforks));

**Comment by ChainQuery** [comment]
@Hannott @jameshilliard Thx, ACK

**Comment by jameshilliard** [comment]
@Hannott it might also be good to keep the version check and have this operate in an either or fashion although I'm not sure what situation that would be an issue

**Comment by Hannott** [comment]
@jameshilliard I see that BitcoinUnlimited does not support the softforks parameter, but I doubt BU is used for mining. That doesn't seem to be that forks intention anyway.

Not sure it's necessary to check for it.

**Comment by jtoomim** [comment]
It looks like the code checks for the presence of a BIP65 flag in 'softforks', but it doesn't actually check the value of that flag. While this may work in practice, I think you should probably actually check the value of the flag, since it's theoretically possible that we might decide to roll back BIP65 support.

Other than that, utACK.

**Comment by jameshilliard** [comment]
@jtoomim rolling back would be a hardfork from my understanding 

maybe v15 chain fork activation should be based off of the output from getblockchaininfo instead of the percentage of p2pool shares that way non-upgraded users would get excluded right away when BIP65 activates

**Comment by Hannott** [comment]
@jtoomim I don't think that's how it works. The rpc return value does not state whether the current version of bitcoind supports a given softfork or not, only the state of that fork. It was my understanding that if a softfork is present in this list, the support for it is a given.

    "softforks" : [
        {
            "id" : "bip65",
            "version" : 4,
            "enforce" : {
                "status" : true,
                "found" : 822,
                "required" : 750,
                "window" : 1000
            },
            "reject" : {
                "status" : false,
                "found" : 822,
                "required" : 950,
                "window" : 1000
            }
        }
    ]

**Comment by Hannott** [comment]
@gavinandresen, can you confirm? You said "The getblockchaininfo RPC call is the correct way to judge whether or not any particular soft-fork is known."

Does known mean support as well?

**Comment by gavinandresen** [comment]
Yes, if the BIP number is in the array that means bitcoind understands and will validate with those rules.

**Comment by Hannott** [comment]
Thanks. Fixed up whitespacing. Ready to merge unless anyone have any technical objections.

**Comment by jtoomim** [comment]
My mistake. I missed that the "status" bit was under the "enforce" key.

**Comment by jtoomim** [comment]
I'm running this code now.

**Comment by Hannott** [comment]
Pinging @forrestv any objections?

**Comment by forrestv** [comment]
Yes, this breaks CHECK_VERSION, and, as a result, any of the altcoin P2Pools that rely on it. In addition, it would check for BIP65 on altcoin P2Pools, which might not be desirable.

I'll clean it up in a way that works for everyone right now. Not much time left either... BIP65 takes effect in less than a day..!

**Comment by forrestv** [comment]
Please test the change applied to the master branch to make sure that it works for you.

**Pull request closed without merging**
