### PR TITLE
Make sure P2Pool is compliant with the CSV softfork

### PR DESCRIPTION
**Pull request by veqtrus**

### CODE REVIEW

**Comment by forrestv** [comment]
Thanks for this.

Sorry that I'm not monitoring it more closely, but where can I see the current state of the Bitcoin network switchover?

**Comment by NicolasDorier** [comment]
bitcoin.sipa.be/ver9-2k.png

**Comment by veqtrus** [comment]
To add to what @NicolasDorier wrote there will be a 2016 block (diff. retarget) grace period after 95% is achieved.

**Comment by squidicuzz** [comment]
Running this and it looks good, shares are being accepted as version 16.

**Comment by ilsawa** [comment]
I use pypy to run p2pool but I error occurs:
`   File "/opt/sha256d/p2pool-btc/p2pool/bitcoin/helper.py", line 26, in <genexpr>
     softforks_supported |= set(item['id'] for item in (yield bitcoind.rpc_getblockchaininfo()).get('bip9_softforks', [])) exceptions.TypeError: string index must be an integer, not str`

**Comment by veqtrus** [comment]
@ilsawa when you call the `getblockchaininfo` RPC method does the response contain `bip9_softforks`?

**Comment by ilsawa** [comment]
yes it contained:
```
bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 414657,
  "headers": 414657,
  "bestblockhash": "00000000000000000012ca1d57564cb5a851a896ca9eed014d4dc1f1f917e736",
  "difficulty": 199312067531.243,
  "mediantime": 1464979859,
  "verificationprogress": 0.9999989199857607,
  "chainwork": "0000000000000000000000000000000000000000001b4b1ab1b25169f1b9a0c6",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "enforce": {
        "status": true,
        "found": 1000,
        "required": 750,
        "window": 1000
      },
      "reject": {
        "status": true,
        "found": 1000,
        "required": 950,
        "window": 1000
      }
    }, 
    {
      "id": "bip66",
      "version": 3,
      "enforce": {
        "status": true,
        "found": 1000,
        "required": 750,
        "window": 1000
      },
      "reject": {
        "status": true,
        "found": 1000,
        "required": 950,
        "window": 1000
      }
    }, 
    {
      "id": "bip65",
      "version": 4,
      "enforce": {
        "status": true,
        "found": 1000,
        "required": 750,
        "window": 1000
      },
      "reject": {
        "status": true,
        "found": 1000,
        "required": 950,
        "window": 1000
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "started",
      "bit": 0,
      "startTime": 1462060800,
      "timeout": 1493596800
    }
  }
}
```

**Comment by veqtrus** [comment]
My bitcoind return a list while yours a dictionary. Are you using Classic?

```
...
 "bip9_softforks": [
    {
      "id": "csv",
      "status": "started"
    }
  ]
...
```

**Comment by ilsawa** [comment]
This is a compilation of source code https://github.com/bitcoin/bitcoin.git
```
bitcoin-cli --help
Bitcoin Core RPC client version v0.12.99.0-239d419
```

**Comment by ilsawa** [comment]
the same in the latest version on github:

```
bitcoin-cli --help
Bitcoin Core RPC client version v0.12.99.0-a80de15
```
```
...
  "bip9_softforks": {
    "csv": {
      "status": "started",
      "bit": 0,
      "startTime": 1462060800,
      "timeout": 1493596800
    }
  }
}

```

**Comment by veqtrus** [comment]
Argh they changed it in bitcoin/bitcoin#7863.

**Comment by ilsawa** [comment]
Many owners of nodes (those whom I know) will have the same error.
They also compile the latest version of the daemon
How to avoid this mistake?

**Comment by veqtrus** [comment]
I will make it recognise both variants. I guess it could be done with one RPC request as well.

**Comment by ilsawa** [comment]
Thank you.

**Comment by veqtrus** [comment]
@ilsawa can you try veqtrus@db9e7cd3e6f643b3ee31063ef3aef60902adb36b?

**Comment by ilsawa** [comment]
@veqtrus it works

**Pull request merged**
